import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Google clone app",
  description: "Generated by create next app, for study purposes",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative min-h-screen">
        
        {children}
        
        {/* FOOTER */}
        <Footer />
        </body>
    </html>
  );
}
